version: '3.8'

services:
  soom-gpt:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        - nodeVersion=${NODE_VERSION}
        - devPort=${DEV_PORT}
        - author=${AUTHOR}
    container_name: soom-gpt_c
    ports:
      - ${DEV_PORT}:${DEV_PORT}
    volumes:
      - ../app:/app_dev/app
      - ../assets:/app_dev/assets
      - ../components:/app_dev/components
      - ../hooks:/app_dev/hooks
      - ../lib:/app_dev/lib
      - ../public:/app_dev/public
    stdin_open: true
    tty: true

volumes:
  soom_project_v:
